### ISSUE TITLE
Dockerfile installs most recent Tensorflow

### ISSUE THREAD

**Issue by AdrianRoggenbach** [PTRRupprecht/Spikefinder-Elephant#3]
The Dockerfile installs at the moment the most recent tensorflow-gpu version, which leads to the following error in [ln 5] of Demo.ipy:
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Changing the command 'pip install tensorflow-gpu' in line 31 of docker/Dockerfile to:
pip install tensorflow-gpu=1.0
fixed this problem for me.

Could you insert this fix into the Dockerfile? I guess this issue occurs for everybody how creates the docker image.

**Comment by PTRRupprecht** [comment]
Thanks for finding this out. When we wrote the Dockerfile, probably tensorflow-gpu=1.0 was installed automatically. - I've fixed it and used your suggestion.

**Comment by AdrianRoggenbach** [comment]
Thanks!
